apiVersion: v1
kind: Service
metadata:
  name: rds-mysql
  namespace: rds-webapp
spec:
  type: ExternalName
  externalName: webapp.c50wyk0s40tz.us-east-1.rds.amazonaws.com
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
